# Autogenerated by devscripts/update-version.py

__version__ = '2024.10.12.071141'

RELEASE_GIT_HEAD = 'b7b973e1fbdc043c220d3ab5c42d183d03ad7e1b'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'observeroftime02/yt-dlp-daily'

ORIGIN = 'observeroftime02/yt-dlp-daily'

_pkg_version = '2024.10.12.071141'
