# Autogenerated by devscripts/update-version.py

__version__ = '2024.02.24.053749'

RELEASE_GIT_HEAD = '464aa5e6b0992f0cec290049e9635bb47f5645f3'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'observeroftime02/yt-dlp-daily'

ORIGIN = 'observeroftime02/yt-dlp-daily'

_pkg_version = '2024.02.24.053749'
