# Autogenerated by devscripts/update-version.py

__version__ = '2025.01.13.155729'

RELEASE_GIT_HEAD = '6f739bae556e0f1ebbc746f214429f8ef899a018'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'observeroftime02/yt-dlp-daily'

ORIGIN = 'observeroftime02/yt-dlp-daily'

_pkg_version = '2025.01.13.155729'
